### ISSUE TITLE
Can't create a pull request

### ISSUE THREAD

**Issue by stemy2** [rms-open-letter/rms-open-letter.github.io#383]
Hello,

I'd like to add my signature to the said petition, but i can't add it through a pull request. After clickibg on "new" in the PR section, i'm redirected to another page with a button named "add a pull request" that appears to be inactive and does literally nothing when i click on it. And i don't understand why.

**Comment by geofft** [comment]
You'll need to submit a pull request through a fork. You can do one of two things:

1. Create a fork of the project with the "Fork" button, clone the fork and edit the file there, and then submit a pull request - it should give you the option to create one from your fork. (If you're using the Git command line, it should give you a little URL once you push.)
2. GitHub has a web UI for editing files. Click on the pencil icon at the top right of https://github.com/rms-open-letter/rms-open-letter.github.io/blob/main/index.md (labeled "Fork this project and edit this file"), and GitHub will automatically make a fork, commit your edit, and prompt you to make a pull request.

**Comment by ehashman** [comment]
Hi @stemy2, feel free to also include your name and optionally any affiliations you'd like to add in this issue and I'd be happy to add the name for you.

**Comment by ChadFacts** [comment]
If someone doesn't know how to use GitHub- do they belong on this page in the first place? Aren't you just loading your form with people who likely don't even know what FOSS is, and are random bandwagons from Twitter?

**Comment by pieterdp** [comment]
> 
> 
> If someone doesn't know how to use GitHub- do they belong on this page in the first place? Aren't you just loading your form with people who likely don't even know what FOSS is, and are random bandwagons from Twitter?

You can be civil and make a point.

**Comment by Jan200101** [comment]
> > If someone doesn't know how to use GitHub- do they belong on this page in the first place? Aren't you just loading your form with people who likely don't even know what FOSS is, and are random bandwagons from Twitter?
> 
> You can be civil and make a point.

it is a serious point point though
it seems as if people from all places, with no and a boat load of IT knowledge, are being asked to sign this but to me this devalues this entire thing because half the people on it might not even really know what they are signing, the background behind it and so on

**Comment by artlogic** [comment]
> it seems as if people from all places, with no and a boat load of IT knowledge, are being asked to sign this but to me this devalues this entire thing because half the people on it might not even really know what they are signing, the background behind it and so on

I'm not certain that lack of knowledge of how to use GitHub should preclude someone from signing this letter, or lead us to make judgements about their knowledge of the issues at hand.

**Comment by Jan200101** [comment]
> > it seems as if people from all places, with no and a boat load of IT knowledge, are being asked to sign this but to me this devalues this entire thing because half the people on it might not even really know what they are signing, the background behind it and so on
> 
> I'm not certain that lack of knowledge of how to use GitHub should preclude someone from signing this letter, or lead us to make judgements about their knowledge of the issues at hand.

My point was not going aginst the person making this issue but rather in general
but you bring up a great point
Github is the largest version control service there is and has streamlined its web interface to the point where anyone with no tech knowledge can edit a simple plain text file but I digress.

the real problem is that people that are being pulled in just to expand the list are next to people who are skilled in their field which creates a disconnected between the value of those signatures and pulls everyone down.

Yes I can tell a cook that their food is bad but what I say has very little meaning because I am in a position where I do not understand his work or the situation around him
