### ISSUE TITLE
Expanding scope: revoking copyright assignments

### ISSUE THREAD

**Issue by Jan200101** [rms-open-letter/rms-open-letter.github.io#756]
**THIS IS A COPY OF #120 TO CONTINUE DISCUSSION ABOUT THIS**
While I am not in agreement with the original issue I do believe discussion about it should be held 

```
 richfelker (Author)

This obviously can't be done in the existing letter, but a proposal I got a lot of positive response to
on Twitter was giving a letter like this some teeth by pledging to withdraw copyright assignment if
the conditions are not met. If a lot of actual GNU project contributors sign on to that, it would put
individual GNU project maintainers in a position of having to accept contributions incompatible
with FSF policy, forcing a split from the FSF and extricating them from the FSF's control and influence.

Original proposal thread is here: https://twitter.com/RichFelker/status/1374111037985808398
```

```
 shenlebantongying

Just admit that you are jealous about gcc/glibc. This proposal is obviously not related to RMS or
FSF at all. You just an opportunist who want to drag down gcc/glibc.

GPL is a common argument between so many developers and real open source companies.

Why the fuck you want to split the community for no actual value? Wasting everyone'e energy and time.

Even they are forked from FSF, those long-time glibc contributors and users will still give no shit to your musl
```

```
 nukeop

This is just about sabotaging the free software movement through acts analogous to terrorism and blackmail.
```

```
 richfelker (Author)

No, it's about saving the movement from someone who cares only about himself and not all the
damage he's done to it by his behavior and continued presence.
```

```
nukeop

RMS has already done more for free software than any of the people on the list. You're joining a mob
to feel righteous. And maybe to exercise power over somebody unable to defend himself, to feel in
control for a moment.

```

**Comment by Jan200101** [comment]
the original issue has been restored but not unlocked, keeping this open

**Comment by rhonda** [comment]
So nukeop, you are saying that if only a person has done enough good they should be allowed to do whatever they please regardless of what impact that has on others? I'm sorry, that's not how a society functions and works.

People have to be accountable for their actions regardless their state in society, and a defense on that grounds is so utterly disturbing that I can't grasp how you came to that thought process.

**Comment by brown121407** [comment]
If you think that holding copyright hostage until RMS is expelled is a good idea, read the following paragraph. If not, feel free to skip it.

If you want to hold RMS accountable for whatever, that's fine, go for it! But don't threaten to disrupt the stability of important free software projects just cause you don't like the man and his ideas. There don't need to be free software projects (of any importance at all) threatened because of this. There sure are ways to resolve this conflict without such disgusting ultimatums (really, the situation would be disgusting for both sides). Some of us depend on free software (as most should do) and we don't want to see pieces of it being called ransom. In my opinion, a _civil_, _open minded_ and _in good faith_ dialogue between the ones opposing RMS and RMS himself would do much more good to the resolution of the conflict than this.

@rhonda 

> So nukeop, you are saying that if only a person has done enough good they should be allowed to do whatever they please regardless of what impact that has on others? I'm sorry, that's not how a society functions and works.
> 
> People have to be accountable for their actions regardless their state in society, and a defense on that grounds is so utterly disturbing that I can't grasp how you came to that thought process.

nukeop didn't explicitly say what you put in their mouth. I think it would be more appropriate to first ask if what you understood from their discourse is what they really wanted to express, e.g.:

> nukeop, are you saying that if only a person has done enough good they should be allowed to do whatever they please regardless of what impact that has on others?

and wait for their response before continuing.
