### ISSUE TITLE
You ought to be ashamed of yourselves.

### ISSUE THREAD

**Issue by RyanFleck** [rms-open-letter/rms-open-letter.github.io#949]
Hello Contributors,

**RMS** may not conform to your societal standards, but condemning the man (him, or Torvalds, who also comes under fire,) marrs your reputation, and not his.

> He has shown himself to be misogynist, ableist, and transphobic, among other serious accusations of impropriety.

I have met RMS in person, (had Chinese food with him, in fact,) and though he may ignore some social conventions, he is a person who has very valuable and unique opinions, and a force to be reckoned with. These accusations appear to be, while not baseless, motivated by an extremely twisted socio-political ideology.

**Shame on you for bringing cancel culture into the world of software.**

**Comment by terceranexus6** [comment]
The freedom of the software movement as he himself supported in its creation is all about community and evolving technology not as a single person but as a group, creating needed work without borders. Willing to put that aside for getting the attention spot without even an attempt of making the people who feel bad about the general message he has sent through the last years against communities who want to support free software feels very disrespectful. 

You are speaking about "cancel culture", but it's about respect the people who are in need of free software (and are willing to support and build over it) in their discourse and feel attacked. And by the way your own experience is not enough against a fact, all you are doing is feeling uncomfortable about listening and evolving as a community because you feel like, personally, don't want to get out your comfort zone. That doesn't seem very community supportive or evolving-like. Self criticism is a necessity in order to improve any group. You are only demonstrating to be supporting a lobby, not a movement.

**Comment by silentjet** [comment]
> The freedom of the software movement as he himself supported in its creation is all about community and evolving technology not as a single person but as a group, creating needed work without borders. Willing to put that aside for getting the attention spot without even an attempt of making the people who feel bad about the general message he has sent through the last years against communities who want to support free software feels very disrespectful.
> 
> You are speaking about "cancel culture", but it's about respect the people who are in need of free software (and are willing to support and build over it) in their discourse and feel attacked. And by the way your own experience is not enough against a fact, all you are doing is feeling uncomfortable about listening and evolving as a community because you feel like, personally, don't want to get out your comfort zone. That doesn't seem very community supportive or evolving-like. Self criticism is a necessity in order to improve any group. You are only demonstrating to be supporting a lobby, not a movement.

You are throwing a standard SJW slogans here. Please think about that. Ocasionally try to avoid such slogans. Ok?

Can you proof that this person (RMS) ever did massive discrimination acts like all of you crying about?
